export const GOMBE_AREAS = [
  "Tudun Wada",
  "Jauro Mato",
  "Gwomti",
  "Pantami",
  "Bolari",
  "Nasarawo",
  "GRA",
  "Shamaki",
  "Doma",
  "Bajoga",
  "Bauchi Road",
  "Kumo Road",
  "Kaltungo Road",
  "Nafada Road",
  "Bye‑Pass",
  "Danmarke",
  "Doma Jankada",
  "Kwami Road",
  "Biya",
  "Yelwa",
  "Nafada",
  "Langa",
  "Kumo",
  "Katon Karfe",
  "Dankama",
  "Kafin Maiyaki",
  "Kwami",
  "Funakaye",
  "Billiri",
  "Kaltungo",
  "Danbatta",
  "Tumfure",
  "Kwami Central",
  "Kwami East",
  "Kwami West",
] as const;

export const CATEGORY_ICONS: Record<string, string> = {
  Tailors: "✂️",
  Mechanics: "🔧",
  "Phone Repair": "📱",
  Electricians: "⚡",
  Welders: "🔨",
  Barbers: "💇",
  Caterers: "🍽️",
  Builders: "🏗️",
  "Computer Cafe": "💻",
  Salons: "💅",
  "Home Appliances": "🛋️",
  Plumbing: "🚿",
  Cleaning: "🧽",
};

export const CATEGORY_COLORS: Record<string, string> = {
  Tailors: "bg-purple-50 text-purple-700 border-purple-200",
  Mechanics: "bg-blue-50 text-blue-700 border-blue-200",
  "Phone Repair": "bg-cyan-50 text-cyan-700 border-cyan-200",
  Electricians: "bg-yellow-50 text-yellow-700 border-yellow-200",
  Welders: "bg-orange-50 text-orange-700 border-orange-200",
  Barbers: "bg-pink-50 text-pink-700 border-pink-200",
  Caterers: "bg-red-50 text-red-700 border-red-200",
  Builders: "bg-stone-50 text-stone-700 border-stone-200",
  "Computer Cafe": "bg-indigo-50 text-indigo-700 border-indigo-200",
  Salons: "bg-rose-50 text-rose-700 border-rose-200",
  "Home Appliances": "bg-teal-50 text-teal-700 border-teal-200",
  Plumbing: "bg-sky-50 text-sky-700 border-sky-200",
  Cleaning: "bg-lime-50 text-lime-700 border-lime-200",
};